In [1]:
import pandas as pd
import numpy as np

In [15]:
orbits = pd.read_json("allcometels.json")
orbits.columns.tolist()

['Orbit_type',
 'Provisional_packed_desig',
 'Year_of_perihelion',
 'Month_of_perihelion',
 'Day_of_perihelion',
 'Perihelion_dist',
 'e',
 'Peri',
 'Node',
 'i',
 'H',
 'G',
 'Designation_and_name',
 'Ref',
 'Epoch_year',
 'Epoch_month',
 'Epoch_day',
 'Comet_num']

In [17]:
orbits["Orbit_type"] + orbits["Provisional_packed_desig"]

0       C.53P010
1       C/56K010
2       C240V010
3       C390Q010
4       C400F010
          ...
4621         NaN
4622         NaN
4623         NaN
4624         NaN
4625         NaN
Length: 4626, dtype: object

In [ ]:
orbits = orbits[orbits["Orbit_type"].isin(["P","D","A"])]
orbits = orbits[orbits["Orbit_type"].isin(["A"])]

In [7]:
orbits

,Orbit_type,Provisional_packed_desig,Year_of_perihelion,Month_of_perihelion,Day_of_perihelion,Perihelion_dist,e,Peri,Node,i,H,G,Designation_and_name,Ref,Epoch_year,Epoch_month,Epoch_day,Comet_num
111,D,H66G010,2024,10,29.0330,0.402530,0.852190,175.6970,93.5440,8.7180,9.0,4.0,D/1766 G1 (Helfenzrieder),"26, 114",2023.0,2.0,25.0,NaN
113,D,H70L010,1779,1,2.1333,5.368127,2.059835,190.2454,338.0274,167.4132,9.0,4.0,D/1770 L1 (Lexell),"3, 245",2022.0,8.0,9.0,NaN
294,D,I84O010,2020,8,8.3364,1.320983,0.571584,339.8357,332.8886,9.3108,9.0,4.0,D/1884 O1 (Barnard),"89, 256",2023.0,2.0,25.0,NaN
302,D,I86K010,2025,6,18.4480,1.887706,0.468375,208.4746,39.1645,10.9263,9.0,4.0,D/1886 K1 (Brooks),"89, 256",2023.0,2.0,25.0,NaN
329,D,I95Q010,2025,9,5.2067,1.388475,0.627062,199.2396,135.8068,13.5278,9.0,4.0,D/1895 Q1 (Swift),"13, 428",2023.0,2.0,25.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4621,P,NaN,2026,3,19.8177,3.692884,0.475337,180.0998,275.2087,8.6041,10.0,4.0,509P/Catalina,MPEC 2026,2025.0,11.0,21.0,509.0
4622,P,NaN,2026,9,9.2335,4.875160,0.248043,86.6870,280.6683,8.2276,9.5,4.0,510P/Boattini,MPEC 2025,2025.0,11.0,21.0,510.0
4623,P,NaN,2025,7,11.0346,2.295996,0.237237,81.2258,271.0275,14.7853,17.1,4.0,511P/PANSTARRS,MPEC 2026,2025.0,11.0,21.0,511.0
4624,P,NaN,2026,12,4.8753,4.801461,0.157395,308.7038,73.7451,12.5688,10.0,4.0,512P/PANSTARRS,MPEC 2025,2025.0,11.0,21.0,512.0
4625,P,NaN,2025,6,13.7756,3.253644,0.551550,304.8674,56.9970,21.3856,11.0,4.0,513P/Broughton,MPEC 2026,2025.0,11.0,21.0,513.0

In [9]:
orbits['Tp'] = 2454466

/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/ipykernel_43405/866275947.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orbits['Tp'] = 2454466

In [12]:
# calculate
orbits["a"] = orbits["Perihelion_dist"] / (1 - orbits["e"])

r = orbits['a']*(1+orbits['e']/2)
def add_vis(orb,param):
    orb['vis_'+str(param)] = (5*np.log10(np.maximum(r,1)*(np.maximum(r,1)-param))+orb['H']).astype(float)
    orb['vis_q_'+str(param)] = (5*np.log10(np.maximum(orb["Perihelion_dist"],1)*(np.maximum(orb["Perihelion_dist"],1)-param))+orb['H']).astype(float)

# These just happen to be ones that seem to work well, but it is open to tuning.
add_vis(orbits,0.6)
add_vis(orbits,-.1)
add_vis(orbits,-.2)

/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/ipykernel_43405/3176425022.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orbits["a"] = orbits["Perihelion_dist"] / (1 - orbits["e"])
/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/ipykernel_43405/3176425022.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orb['vis_'+str(param)] = (5*np.log10(np.maximum(r,1)*(np.maximum(r,1)-param))+orb['H']).astype(float)
/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/ipykernel_43405/3176425022.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orb['vis_q_'+str(param)] = (5*np.log10(np.maximum(orb["Perihelion_dist"],1)*(np.maximum(orb["Perihelion_dist"],1)-param))+orb['H']).astype(float)
/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/ipykernel_43405/3176425022.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orb['vis_'+str(param)] = (5*np.log10(np.maximum(r,1)*(np.maximum(r,1)-param))+orb['H']).astype(float)
/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/ipykernel_43405/3176425022.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orb['vis_q_'+str(param)] = (5*np.log10(np.maximum(orb["Perihelion_dist"],1)*(np.maximum(orb["Perihelion_dist"],1)-param))+orb['H']).astype(float)
/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/ipykernel_43405/3176425022.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orb['vis_'+str(param)] = (5*np.log10(np.maximum(r,1)*(np.maximum(r,1)-param))+orb['H']).astype(float)
/var/folders/q_/q72gghqx0dbbrygb127lyk2m0000gp/T/ipykernel_43405/3176425022.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orb['vis_q_'+str(param)] = (5*np.log10(np.maximum(orb["Perihelion_dist"],1)*(np.maximum(orb["Perihelion_dist"],1)-param))+orb['H']).astype(float)

In [13]:
mlcols = ['H', 'Peri', 'Node', 'i', 'Tp', 'vis_0.6', 'vis_q_-0.1', 'vis_q_-0.2', 'orbital_period_sync', 'Perihelion_direction_x_e', 'Perihelion_direction_y_e','Is_Past_Threshold']

orbits[mlcols]

KeyError: "['orbital_period_sync', 'Perihelion_direction_x_e', 'Perihelion_direction_y_e', 'Is_Past_Threshold'] not in index"

In [1]:
# read in all the lines from CmtObs.txt and output them to CmtObsFiltere.txt if they start with "    P"
with open("CmtObs.txt", "r") as infile, open("CmtObsFiltered.txt", "w") as outfile:
    for line in infile:
        if line.startswith("    A") or line.startswith("    P") or line.startswith("    D"):
            outfile.write(line)

In [18]:
comet = pd.read_json("https://www.minorplanetcenter.net/Extended_Files/allcometels.json.gz",compression='gzip')

In [20]:
comet[comet["Designation_and_name"].str.contains("Ye")]

,Orbit_type,Provisional_packed_desig,Year_of_perihelion,Month_of_perihelion,Day_of_perihelion,Perihelion_dist,e,Peri,Node,i,H,G,Designation_and_name,Ref,Epoch_year,Epoch_month,Epoch_day,Comet_num
3410,C,K15V62L,2017,8,27.9808,2.729223,1.001999,129.0403,95.2868,165.8322,8.0,4.0,C/2015 VL62 (Lemmon-Yeung-PANSTARRS),MPC115881,2023.0,2.0,25.0,NaN
3586,C,K19K040,2019,6,16.4136,2.259388,0.999037,139.7697,180.1647,105.3058,12.5,4.0,C/2019 K4 (Ye),MPC119997,2019.0,6.0,6.0,NaN
4001,P,K25UA9X,2025,8,14.2601,2.569628,0.324032,276.1355,197.9748,3.1813,13.7,4.0,P/2025 UX109 (Ye),MPEC 2026,2025.0,11.0,21.0,NaN
4271,P,NaN,2025,11,2.3735,3.358190,0.205072,208.8712,30.8807,11.2220,13.0,4.0,172P/Yeung,MPEC 2025,2025.0,11.0,21.0,172.0